### ISSUE TITLE
Got a ValueError when using the pretrained model to segment images

### ISSUE THREAD

**Issue by YaoZhang93** [ReubenDo/U-HVED#10]
Hi Reuben,

Thanks for your code.
I am trying to use the pretrained model you provided to reproduce the results.
However, when I run:
python inference.py -n u_hemis -t1 ./data/BRATS2018/HGG3_T1.nii.gz -t2 ./data/BRATS2018/HGG3_T2.nii.gz  -t1c ./data/BRATS2018/HGG3_T1c.nii.gz -fl ./data/BRATS2018/HGG3_Flair.nii.gz

I got an error that said:

------------------------------------------
Number of subjects 2, input section names: ['T1', 'subject_id', 'T1c', 'Flair', 'T2']
Dataset partitioning:
-- training 190 cases (9500.00%),
-- validation 95 cases (4750.00%),
-- inference 0 cases (0.00%).

CRITICAL:niftynet: Reader required input section name [T1], but in the filename list the column is empty.
CRITICAL:niftynet: file_list parameter should be a pandas.DataFrame instance and has input section name [T1] as a column name.
CRITICAL:niftynet: Reader requires section(s): ['T1', 'T1c', 'T2', 'Flair']
CRITICAL:niftynet: Configuration input sections are: ['T1', 'subject_id', 'T1c', 'Flair', 'T2']
Traceback (most recent call last):
  File "/apdcephfs/share_1290796/medzhang_data/Task/missing_modal/U-HVED/uhved_python/bin/net_run", line 8, in <module>
    sys.exit(main())
  File "/apdcephfs/share_1290796/medzhang_data/Task/missing_modal/U-HVED/uhved_python/lib/python3.6/site-packages/niftynet/__init__.py", line 141, in main
    app_driver.initialise_application(system_param, input_data_param)
  File "/apdcephfs/share_1290796/medzhang_data/Task/missing_modal/U-HVED/uhved_python/lib/python3.6/site-packages/niftynet/engine/application_driver.py", line 167, in initialise_application
    data_param, app_param, self.data_partitioner)
  File "/apdcephfs/share_1290796/medzhang_data/Task/missing_modal/U-HVED/extensions/multi_modal_application.py", line 97, in initialise_dataset_loader
    data_param, task_param, file_list) for file_list in file_lists]
  File "/apdcephfs/share_1290796/medzhang_data/Task/missing_modal/U-HVED/extensions/multi_modal_application.py", line 97, in <listcomp>
    data_param, task_param, file_list) for file_list in file_lists]
  File "/apdcephfs/share_1290796/medzhang_data/Task/missing_modal/U-HVED/uhved_python/lib/python3.6/site-packages/niftynet/io/image_reader.py", line 158, in initialise
    raise ValueError
ValueError
------------------------------------------

I have checked the version of tensorflow and niftynet.
Do you have any idea about what is wrong here?

Best,
Yao

**Comment by LightA2** [comment]
Hello, I run the code and you have the same reaction to the above problem, how do you solve the above problem, specifically where there is a problem, how to solve it
